### ISSUE TITLE
Deployment with AWS or GCC

### ISSUE THREAD

**Issue by sly8787** [mblaschke/TYPO3-docker-boilerplate#103]
Is there any documentation about deployment on AWS or GCC?

**Comment by mblaschke** [comment]
There is currently a refactoring in work with new base images:
https://github.com/webdevops/php-docker-boilerplate/tree/feature/refactoring

This refactoring also supports deployment tasks (with ansible) or just copy your sourcode into your docker containers. There is already one cloud example.
