### ISSUE TITLE
max_execution_time in development.ini not reached because of timeout from fastcgi

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-docker-boilerplate#105]
In the current develop version the max_execution_time in etc/php/development/production.ini is mostly not reached because timeout of fastcgi is set to 30 sec

**Comment by mblaschke** [comment]
WIll be available in some minutes/hours (depends on workload of docker hub)

You need to fetch the new containers with:
`docker pull -a webdevops/php-apache`
or/and
`docker pull -a webdevops/php-nginx`
