### ISSUE TITLE
Internal Mailserver Validates E-Mail adresses

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/TYPO3-docker-boilerplate#109]
Current Behaviour:
Internal Mailserver Validates E-Mail adresses on submission.
When used for development, a developer may use random generated email adresses for testing.
This results in the mailer demon, responding with failed delivery.

Solution:
Prevent Check for Valid Email Address

**Comment by josefglatz** [comment]
@PanadeEdu I can't reproduce this behaviour with develop branch and the default mail-sandbox "mailhog".

> I tested it with e.g. `
$nachricht = 'checkthis';
mail('benutzer@ukasd', 'Mein Betreff', $nachricht);
mail('benutzer@tatzel', 'Mein Betreff', $nachricht);
mail('benutzer@example.asdf', 'Mein Betreff', $nachricht);`

![image](https://user-images.githubusercontent.com/2861556/44863535-a68dcb00-ac7d-11e8-9170-944b2da5abd3.png)
