### ISSUE TITLE
TYPO3 v8 requires PHP7+

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#112]
Hello!

The TYPO3 v8 development cyclus is starting. TYPO3 v8 requires PHP7+, see https://typo3.org/news/article/kicking-off-typo3-v8-development/

TYPO3 v8.0  --  Mar 22nd, 2016  --  Sprint Release

The current dockerfiles support PHP5+

Unfortunately I can't support with this, as I am not experienced in packing docker files.

Kind Regards

\Elmar

**Comment by mblaschke** [comment]
PHP 7.x support is already available in `develop` Branch.

**Comment by elmar-hinz** [comment]
Dockerfile.development: ubuntu-16.04 -> PHP 5.6 and 7.0 (xenial)   LTS

How do you select the PHP version?

**Comment by elmar-hinz** [comment]
The TYPO3 master branch already breaks with:

"This version of TYPO3 CMS requires PHP 7.0 or above"

**Comment by mblaschke** [comment]
Look at `Dockerfile.development`:

You can use eg. `webdevops/php-apache:debian-8-php7` or `webdevops/php-apache:ubuntu-16.04-php7`

But beware that xenial is not stable right now

**Comment by elmar-hinz** [comment]
Thank you. I understand the naming system now. Installed webdevops/php-apache:debian-8-php7.

**Comment by mblaschke** [comment]
`debian-9` will be currently fixed with new images, found some issues.
Build is running: https://build.webdevops.io/build/45bf7960ea04b1626a45849656dc4d0b

You can join us at slack: https://webdevops.io/slack/

**Comment by mblaschke** [comment]
PHP 7 is now available with tag `alpine-3-php7`, `debian-8-php7`, `debian-9` and `ubuntu-16.04`.

For TYPO3 please use `ubuntu-16.04`
