### ISSUE TITLE
Getting the development branch running

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#113]
The master branch is working as expected. Stopping it and trying the development branch in a separated clone directory.

I get the containers started and "make state" shows the mapping "0.0.0.0:8000->80/tcp".

Opening the browser "http://192.168.56.2:8000/" I expect to see "index.php". Instead I get an error: 

"Google Chrome's connection attempt to 192.168.56.2 was rejected. The website may be down, or your network may not be properly configured."

**Comment by mblaschke** [comment]
Have you rebuild all containers?
- `docker-compose build --no-cache`
- `docker-compose up -d --force-recreate`

**Comment by elmar-hinz** [comment]
That doesn't fix it.

**Comment by elmar-hinz** [comment]
Same issue with 5.0 now. 

I wanted to verify that it is working with 4.0 and tried an install with 4.0.1 but that ends up in an error now.

```
git clone --recursive https://github.com/webdevops/TYPO3-docker-boilerplate.git Test2
cd Test2
git checkout 4.0.1
docker-compose up -d

[...]

Creating test2_storage_1
Creating test2_mysql_1
Creating test2_main_1
ERROR: Container command not found or does not exist.
```

```
docker-compose stop
docker-compose rm --force
docker-compose build --no-cache
docker-compose up -d
```

```
Creating test2_storage_1
Creating test2_mysql_1
Creating test2_main_1
ERROR: Container command not found or does not exist.
```

**Comment by elmar-hinz** [comment]
master branch (5.0.1)

`docker-compose logs`

Endlessly repeating with counting pid: 

```
app_1     | 2016-03-09 10:25:37,009 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | DocumentRoot must be a directory
app_1     | 2016-03-09 10:25:37,024 INFO exited: apached (exit status 1; not expected)
app_1     | 2016-03-09 10:25:38,046 INFO spawned: 'apached' with pid 869
app_1     | AH00526: Syntax error on line 6 of /opt/docker/etc/httpd/global.conf:
```

**Comment by mblaschke** [comment]
Which value does your `WEB_DOCUMENT_ROOT` in `etc/environment.yml` have?
If you pull the newest image you will get a better error message.

If `WEB_DOCUMENT_ROOT=/app/web` then your code have to be in `app/web` on host side :)

**Comment by elmar-hinz** [comment]
- Working with dbea55560aaab6efe3653570582d33f09539f676.
- Fresh download. 
- I didn't change the your defaults. 

```
less etc/environment.yml

# Webserver

# General
WEB_DOCUMENT_ROOT=/app/web/
WEB_DOCUMENT_INDEX=index.php
CLI_SCRIPT=php /app/web/typo3/cli_dispatch.phpsh
```
- Manually creating `app/web/index.php`.

```
docker-compose stop
docker-compose rm --force
docker-compose build --no-cache
docker-compose up -d

docker-compose logs
```

Still the same errors.

```
app_1     | 2016-03-09 13:18:45,772 INFO spawned: 'apached' with pid 1418
app_1     | AH00526: Syntax error on line 6 of /opt/docker/etc/httpd/global.conf:
app_1     | DocumentRoot must be a directory
app_1     | 2016-03-09 13:18:45,821 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-09 13:18:45,837 INFO exited: apached (exit status 1; not expected)
```

**Comment by mblaschke** [comment]
How old are your base images?
`docker images|grep webdevops/`

**Comment by elmar-hinz** [comment]
webdevops/php-apache        debian-8-php7       7c0ef73dc390        7 days ago          859.2 MB
webdevops/php-apache        ubuntu-14.04        2d74dba4a51c        7 days ago          821 MB
webdevops/storage           latest              c1291336196a        7 days ago          673.5 MB
webdevops/php-boilerplate   ubuntu-14.04        f35709c5cdc8        6 months ago        509.1 MB

If base images can get to old, shouldn't there be a kind of versioning to avoid such issues?

**Comment by elmar-hinz** [comment]
```
docker pull webdevops/php-boilerplate
docker images|grep webdevops/


webdevops/php-boilerplate   latest              dc1bf4a8900b        3 days ago          521.5 MB
webdevops/php-apache        debian-8-php7       7c0ef73dc390        7 days ago          859.2 MB
webdevops/php-apache        ubuntu-14.04        2d74dba4a51c        7 days ago          821 MB
webdevops/storage           latest              c1291336196a        7 days ago          673.5 MB
webdevops/php-boilerplate   ubuntu-14.04        f35709c5cdc8        6 months ago        509.1 MB
```

Hmmm ...

**Comment by mblaschke** [comment]
`webdevops/php-boilerplate` is the old base image which isn't used anymore.
`webdevops/php-apache` and `webdevops/php-nginx` are the new ones.

Please try: `docker pull webdevops/php-apache:ubuntu-14.04` (if you use ubuntu 14.04)

**Comment by elmar-hinz** [comment]
```
app_1     | 2016-03-09 14:27:28,642 INFO spawned: 'apached' with pid 1327
app_1     |
app_1     | [WARNING] WEB_DOCUMENT_ROOT does not exists with path "/app/web/"!
app_1     |
app_1     | 2016-03-09 14:27:28,649 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | AH00526: Syntax error on line 6 of /opt/docker/etc/httpd/global.conf:
app_1     | DocumentRoot must be a directory
app_1     | 2016-03-09 14:27:28,726 INFO exited: apached (exit status 1; not expected)
```

```
ElmarHinz@Elmars-MBP> ls -al app/web/
total 8
drwxr-xr-x  2 ElmarHinz  admin  102 Mar  9 14:12 .
drwxr-xr-x  3 ElmarHinz  admin  136 Mar  9 14:11 ..
-rw-r--r--  1 ElmarHinz  admin   18 Mar  9 14:12 index.php
```

**Comment by mblaschke** [comment]
which `docker-compose.yml` do you use? symlink to `docker-compose.development.yml`? 
Make sure the volume path is correct inside the docker-compose.yml :)

**Comment by elmar-hinz** [comment]
```
# copy favorite docker-compose.*.yml to docker-compose.yml
cp docker-compose.development.yml docker-compose.yml
```

https://github.com/webdevops/TYPO3-docker-boilerplate/blob/master/documentation/DOCKER-STARTUP.md

**Comment by mblaschke** [comment]
Can you please contact me via slack for more debugging? I'm not sure if this is really an docker issue.

**Comment by mblaschke** [comment]
Bug cause: Mounting of the directory was buggy
Solution: Fixed the mounting inside vagrant :)
