### ISSUE TITLE
TYPO3 CMS Base Distribution contains http instead of https

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#116]
The TYPO3 CMS Base Distribution, that is downloaded for the initial "app/composer.json", is not part of this project, but maybe it's possible to get it updated or to add a workaround.

Since update to Composer version 1.0.0-beta1, it doesn't accept the http protocol. 

Error msg: 

```
    [Composer\Downloader\TransportException]
    Your configuration does not allow connection to http://composer.typo3.org. 
    See https://getcomposer.org/doc/06-config.md#secure-http for details.
```

When I edit the downloaded app/composer.json to https I can execute it manually after changing into the app directory with "composer install".

```
    "repositories": [
            { "type": "composer", "url": "http://composer.typo3.org/" }
    ],

    "repositories": [
            { "type": "composer", "url": "https://composer.typo3.org/" }
    ],
```

**Comment by elmar-hinz** [comment]
This seems to be fixed in app/composer.json.

Can be closed.

**Comment by josefglatz** [comment]
Thx!
