### ISSUE TITLE
After running for a longer time the app container doesn't stop

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#120]
Directly after starting all containers can be stopped without problems. When running for hours the App container can't be stopped any more. A network issue is reported.

```
Stopping elmarhinz_app_1 ...
Stopping elmarhinz_mysql_1 ... done
Stopping elmarhinz_storage_1 ... done

ERROR: for elmarhinz_app_1  HTTPConnectionPool(host='192.168.56.2', port=2375): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I help myself by stopping the Vagrant based parent machine. 

Guess this is cased by my environment somehow. Anyway, I like to report this in case others observe the same issue.

**Comment by mblaschke** [comment]
Do you have any log informations? `dmesg`, syslog in VM or `docker-compose logs app`?

**Comment by josefglatz** [comment]
@elmar-hinz Are you using the actual develop branch of TYPO3 docker boilerplate? Often a project runs more than 3-4 days within the vagrant-docker-vm without problems. (vmware fusion and parallels)

**Comment by mblaschke** [comment]
Is this still happening with newest images?

**Comment by elmar-hinz** [comment]
Currently writing unit tests without using docker.

I have seen it a few times. I suspect it is related to networking, when the macbook updates it's settings due to the change of the WLAN location.

**Comment by mblaschke** [comment]
You could retry it with `webdevps/php-dev`

**Comment by josefglatz** [comment]
I close the issue due inactivity. Comment if we should reopen it
