### ISSUE TITLE
Q: How to restart php?

### ISSUE THREAD

**Issue by irnnr** [mblaschke/TYPO3-docker-boilerplate#121]
I was able to add/install APCu to the app container by modifying the Dockerfile. However, I'm stuck trying to restart the php-fpm process.

Any hints on how to do that?

**Comment by irnnr** [comment]
A: I stopped, then rebuilt the container using `docker-compose build --no-cache app`. The container now picked up the new extension. 

Docker file:

```
FROM webdevops/php-apache:ubuntu-16.04-php7

ENV PROVISION_CONTEXT "development"

# Deploy scripts/configurations
COPY etc/             /opt/docker/etc/
COPY provision/       /opt/docker/provision/

RUN apt-get update && \
    apt-get install -y php7.0-dev && \
    printf "\n" | pecl install apcu && \
    echo "extension=apcu.so" > /etc/php/7.0/mods-available/apcu.ini && \
    ln -s /etc/php/7.0/mods-available/apcu.ini /etc/php/7.0/fpm/conf.d/20-apcu.ini

RUN /opt/docker/bin/control.sh provision.role boilerplate-main \
    && /opt/docker/bin/control.sh provision.role boilerplate-main-development \
    && /opt/docker/bin/control.sh provision.role.startup boilerplate-deployment \
    && /opt/docker/bin/bootstrap.sh

# Configure volume/workdir
RUN mkdir -p /app/
WORKDIR /app/
```

**Comment by irnnr** [comment]
Adding APCu allows TYPO3 to use it as a cache backend for Extbase object cache...

**Comment by mblaschke** [comment]
Tip: you can use `apt-install` for running apt-get update, install and cleanup.
This script will reduce docker image size by cleanup apt stuff at the end.

**Comment by mblaschke** [comment]
APCu is now available on new images.
