### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http://localhost:8000 - is it running?

### ISSUE THREAD

**Issue by forethoughtde** [mblaschke/TYPO3-docker-boilerplate#126]
hello, 

i receive the following error message when i run the command "docker-compose up -d". I did check that if my docker is running. It is running. 

ERROR: Couldn't connect to Docker daemon at http://localhost:8000 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Can you please help me?

**Comment by mblaschke** [comment]
can you run `docker ps`?

**Comment by forethoughtde** [comment]
I have fixed the problem. It was a mistake from my side. Thanks!
