### ISSUE TITLE
Conflicting docker configurations resulted in a container in excess

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#128]
I started a composer suite while a second one with the same configuration was still running. This resulted not only in an error message about an allocated DB port, as expected, but in a container in excess.

The container in excess was bafba6dc12f4_elmarhinz_mysql_1. 

It showed up by calling: `docker-compose ps`. 

I solved this by removing that container: `docker rm  bafba6dc12f4_elmarhinz_mysql_1`.

**Comment by mblaschke** [comment]
Seems to be a migration from an older docker-compose version. I'm not sure if we can do anything here.

**Comment by elmar-hinz** [comment]
Just wanted to file the event. I think there is nothing to do, but in case that's how to handle it.

Label: wont fix
