### ISSUE TITLE
Support of blackfire.io

### ISSUE THREAD

**Issue by georgringer** [mblaschke/TYPO3-docker-boilerplate#129]
It would be very nice to be able to use blackfire.io

**Comment by mblaschke** [comment]
With images published next night new images with blackfire are available.
See https://github.com/webdevops/Dockerfile/issues/116 and https://github.com/webdevops/Dockerfile/issues/113

For documentation see http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-dev.html
