### ISSUE TITLE
Install apcu by default

### ISSUE THREAD

**Issue by hirnschmalz** [mblaschke/TYPO3-docker-boilerplate#137]
I added the line

```
RUN apt-install php5-apcu
```

to my `Dockerfile.development`. I think it would make sense to always install apcu since TYPO3 CMS want's to use an opcache.

**Comment by mblaschke** [comment]
Added with https://github.com/webdevops/Dockerfile/commit/61c8272fd9063dd656429ffde3854d11a797cc94
