### ISSUE TITLE
MYSQL connect fails during backup/restore

### ISSUE THREAD

**Issue by tbal** [mblaschke/TYPO3-docker-boilerplate#146]
see: https://github.com/webdevops/php-docker-boilerplate/issues/51

**Comment by tbal** [comment]
Fixed with commit d3730bbc4c4666a6744e9a210f56c5c3e290a5db (currently only in develop-branch).

**Comment by guiyomh** [comment]
Hi @tbal 
they are a PR #54(on php-docker-boilerplate) to fix it. Please, wait that it's merge by @mblaschke

**Comment by tbal** [comment]
Tanks @guiyomh!

Fixed with:
https://github.com/webdevops/php-docker-boilerplate/pull/52 and
https://github.com/webdevops/php-docker-boilerplate/pull/54

There is another possible problem regarding the mysql-backup/-restore commands when using unquoted variables with whitespaces in etc/environment.yml, which is handled with PR #163
