### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by thiesschneider** [mblaschke/TYPO3-docker-boilerplate#148]
How do I connect to ssh via terminal or gitlab for example. If I try `ssh -P 10022 localhost` my connection is rejected.

**Comment by manuelbachl** [comment]
found a workaround (thx to @mblaschke ):

add `RUN /opt/docker/bin/control.sh service.enable ssh` to your ~docker-compose.yml~ Dockerfile.development

**Comment by tbal** [comment]
This is now integrated since Jan 20, 2017, see: https://github.com/webdevops/Dockerfile/releases/tag/1.2.4

Example usage:
```
$ ssh -p 10022 root@localhost
$ ssh -p 10022 application@localhost
```

**Comment by thiesschneider** [comment]
thx!
