### ISSUE TITLE
"make" is missing on some hosts

### ISSUE THREAD

**Issue by stucki** [mblaschke/TYPO3-docker-boilerplate#169]
Managing containers using `make up` etc. is very handy while working with this project.
However, the "make" command is missing on many hosts.

While it can be added on Linux and Mac hosts very easily, I couldn't find an easy way to install it on Windows hosts.

If you know how to install it easily on Windows, please let me know. We should mention it in the documentation then.

**Comment by josefglatz** [comment]
Hey stucki, I personally don't use make. I use webdevops/clitools which rely on PHP. Could this also be an option?

**Comment by josefglatz** [comment]
I would say, the easiest thing to install make is via cygwin?

**Comment by stucki** [comment]
Thanks for the feedback, @jousch. Right, clitools may be a workaround for this, I will take a look...
However, I still think that `make <command>` is the easiest way to control Docker. Will post here if I find a simple alternative for it...
