### ISSUE TITLE
Enable URL rewriting for RealUrl when using Nginx

### ISSUE THREAD

**Issue by stucki** [mblaschke/TYPO3-docker-boilerplate#170]
Right now it's only possible to use TYPO3 with RealUrl in the Apache containers using `RewriteEngine on` in `.htaccess`. There is no such way to do this in Nginx.

Currently I'm adding support for URL rewriting by adding the required config through Ansible:

```
diff --git a/provision/roles/boilerplate-main/tasks/bootstrap/web.nginx.yml b/provision/roles/boilerplate-main/tasks/bootstrap/web.nginx.yml
index de750da..204d730 100644
--- a/provision/roles/boilerplate-main/tasks/bootstrap/web.nginx.yml
+++ b/provision/roles/boilerplate-main/tasks/bootstrap/web.nginx.yml
@@ -11,3 +11,11 @@
     owner: root
     group: root
     mode:  0775
+
+- name: Override Nginx location handling
+  template:
+    src:   templates/nginx/10-location-root.conf.j2
+    dest:  /opt/docker/etc/nginx/vhost.common.d/10-location-root.conf
+    owner: root
+    group: root
+    mode:  0775
diff --git a/provision/roles/boilerplate-main/templates/nginx/10-location-root.conf.j2 b/provision/roles/boilerplate-main/templates/nginx/10-location-root.conf.j2
new file mode 100644
index 0000000..2ef6230
--- /dev/null
+++ b/provision/roles/boilerplate-main/templates/nginx/10-location-root.conf.j2
@@ -0,0 +1,3 @@
+location / {
+    try_files $uri $uri/ /index.php$is_args$args;
+}
```

This works well!

However, this enables URL rewriting by default for everyone, and I'm not sure if that is a good thing.
How can it be done instead? (I'm generally wondering about best practice suggestions on how to extend the configuration...)

**Comment by josefglatz** [comment]
@stucki I didn't really tried nginx images for app container so far.

As far as I understand the architecture, it's actually not possible to extend just by files.

What do you think about extending the `/etc/` folder of the boilerplate especially for nginx related files. (like `/etc/nginx/` and make it possible to override files in the container?

**Comment by stucki** [comment]
You mean similar like `etc/` which is added to `/opt/docker/etc/` upon build? Makes sense to me. What does @mblaschke think?

**Comment by josefglatz** [comment]
@stucki could you make a PR for that stuff?

**Comment by stucki** [comment]
@josefglatz Won't do this, sorry. See #200, I'm now using ddev.
