### ISSUE TITLE
XDebug => PhpStorm connection is not working on Mac OS X

### ISSUE THREAD

**Issue by spoonerWeb** [mblaschke/TYPO3-docker-boilerplate#179]
This issue exists when using Docker for Mac!
You need to do following steps:

1. Follow the instructions on https://www.ashsmith.io/docker/get-xdebug-working-with-docker-for-mac/ to create an alias for localhost with the IP `10.254.254.254`
1. Add the line `xdebug.remote_host = 10.254.254.254` to the development.ini
1. Set `xdebug.remote_connect_back = Off` in the development.ini
1. `make rebuild`
1. Setup PhpStorm like mentioned in the documentation
1. Additionally go to PhpStorm => Settings => Languages & Frameworks => PHP => Debug => DBGp Proxy and set **Host** to the IP `10.254.254.254` and **Port** `9001`

Hope, this helps others with that issue.

**Comment by josefglatz** [comment]
This is just necessary when using Docker for Mac? Because I have no problems using XDebug without configuration

**Comment by spoonerWeb** [comment]
Yes, with Docker for Mac!

**Comment by stucki** [comment]
The problem is that the Docker container runs on a VM which does not (seem to) allow connections to the host. When you browse the website, Nginx or Apache think that you are <ip of the vm> and therefore the connection to your host (where PhpStorm is running) does not work.

**Comment by dmitryd** [comment]
To make it work you adjust `etc/php/development.ini` as follows:

```
xdebug.remote_connect_back = off
xdebug.remote_host = docker.for.mac.localhost
```

See [this](https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) for the official Docker information on the matter.

**Comment by josefglatz** [comment]
@spoonerWeb Does the problem still exist?

**Comment by SmithysHub** [comment]
Macos also needs a native proxy - Try this on macos side:
`sudo ifconfig en0 alias 10.254.254.254 255.255.255.0`

**Comment by kkugelmann** [comment]
If you use `xdebug.remote_host = host.docker.internal` instead the configuration is working for all platforms 👍

**Comment by htuscher** [comment]
In addition, if you use a nginx reverse proxy, you'll need to override this:
```
proxy_set_header X-Forwarded-For "host.docker.internal";
```
