### ISSUE TITLE
Support of PHP 7.1

### ISSUE THREAD

**Issue by georgringer** [mblaschke/TYPO3-docker-boilerplate#186]
Currently 7.1 seems not to be supported. Using `FROM webdevops/php-apache-dev:7.1` just brings errors to the Install Tool/Backend

**Comment by josefglatz** [comment]
# PHP Module missing 

- [x] memchached php module is missing

# Problems PHP-FPM
- [x] opening TYPO3 install tool (the initial 123-install-mode is working) throws php-fpm error)

```
app_1         | [httpd:access] 9.typo3.docker:80 172.22.0.7 - - [30/Oct/2017:18:23:59 +0000] "GET /typo3/install.php?install[controller]=layout&install[action]=executeSilentConfigurationUpdate&_=1509387839526 HTTP/1.1" 200 bytesIn:715 bytesOut:319 reqTime:0
app_1         | [30-Oct-2017 18:23:59] WARNING: [pool www] child 375 said into stderr: "*** Error in `php-fpm: pool www': free(): invalid pointer: 0x00007ff175abf25e ***"
app_1         | [Mon Oct 30 18:23:59.801925 2017] [proxy_fcgi:error] [pid 114:tid 140535633184512] [client 172.22.0.7:49732] AH01067: Failed to read FastCGI header, referer: http://9.typo3.docker/typo3/install.php
app_1         | [Mon Oct 30 18:23:59.801967 2017] [proxy_fcgi:error] [pid 114:tid 140535633184512] (104)Connection reset by peer: [client 172.22.0.7:49732] AH01075: Error dispatching request to : , referer: http://9.typo3.docker/typo3/install.php
app_1         | docker.vm:80 172.22.0.7 - - [30/Oct/2017:18:23:59 +0000] "GET /typo3/install.php?install[controller]=layout&install[action]=mainLayout&_=1509387839527 HTTP/1.1" 503 569 "http://9.typo3.docker/typo3/install.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
app_1         | [httpd:access] 9.typo3.docker:80 172.22.0.7 - - [30/Oct/2017:18:23:59 +0000] "GET /typo3/install.php?install[controller]=layout&install[action]=mainLayout&_=1509387839527 HTTP/1.1" 503 bytesIn:693 bytesOut:569 reqTime:0
app_1         | [30-Oct-2017 18:23:59] WARNING: [pool www] child 375 exited on signal 6 (SIGABRT - core dumped) after 90.272471 seconds from start
app_1         | [30-Oct-2017 18:23:59] NOTICE: [pool www] child 430 started
```

**Comment by josefglatz** [comment]
Seams like libpcre is broken.

An actual workaround is to put `pcre.jit=0` into the php.ini (which is /etc/php/development.ini in TYPO3-docker-boilerplate.

After adding the line, build your app container new (`make rebuild` could do the job)

**Comment by tomhatzer** [comment]
We had the same problem. You can fix libpcre using the following manual: https://stackoverflow.com/a/38204958

pcre.jit=0 is a quick fix for this.

So updating to the latest testing version of libpcre should fix the problem with invalid pointers.

**Comment by josefglatz** [comment]
I already tested the quickfix without complete success. Install Tool of 9 master crashed too with jot=0

Von meinem iPhone gesendet

**Comment by josefglatz** [comment]
TYPO3 works with the latest `webdevops/php-apache-dev:7.1` image. According to the issue in the upstream repo was the problem fixed. PCRE extension lib version is now 8.38 (which should be fine)

Just run `docker pull webdevops/php-apache-dev:7.1` to get newest image from Docker hub. Then run `make rebuild` in your TYPO3-docker-boilerplate project dir.

If you have any questions - you've got my phone number ;)
