### ISSUE TITLE
Install php module

### ISSUE THREAD

**Issue by totemusik** [mblaschke/TYPO3-docker-boilerplate#189]
Hello,
first, thanks for your nice work on this docker file.
I am new to docker. Switching from Vagrant to Docker.

I tryed to install the php_mysqli.dll into docker, by including this line into /etc/php/development.ini
extension = php_mysqli.dll

After rebuild this seems not working. php -m don´t shows the module.
Changes on the development.ini are working. I tryed to edit max_input_vars to 5001 and this showed up.

My question is, how to activate / install needed extensions.

Thanks for your help.

regards

Torsten

**Comment by josefglatz** [comment]
Hi, the mysqli PHP extension is already available.

What are you exactly trying? What is the goal? Changing `max_input_vars` is done in another way. (Maybe @hhoechtl can post an example?)

**Comment by josefglatz** [comment]
@totemusik JFYI: https://github.com/webdevops/TYPO3-docker-boilerplate/blob/develop/documentation/CUSTOMIZE.md#install-moreothercustom-php-extensions

**Comment by josefglatz** [comment]
I close the issue, as there where no feedback.
