### ISSUE TITLE
Upgrade to TYPO3 9

### ISSUE THREAD

**Issue by Abdull** [mblaschke/TYPO3-docker-boilerplate#201]
The current TYPO3 setup guide ( https://github.com/webdevops/TYPO3-docker-boilerplate/blob/f4d4b438d32afb5f36cbec9b8b6594a956be6013/documentation/PROJECT-TYPO3.md ) is outdated: Executing `composer create-project typo3/cms-base-distribution app/` will install the latest TYPO3 base distribution, which is currently at version `9.5.0`. 

I encountered the following problems:
* `typo3/cms-base-distribution app` at `9.5.0` does not use directory `web/`, but `public/` -> the mentioned command `touch app/web/FIRST_INSTALL app/.gitkeep` must be updated to `touch app/public/FIRST_INSTALL app/.gitkeep`.
* The Apache/httpd configuration must be updated accordingly to use this `public/` `DocumentRoot`.
* The TYPO3 installation wizard fails with the message `This version of TYPO3 CMS requires PHP 7.2 or above`.

**Comment by rowild** [comment]
What is `make create typo3` supposed to do? (Currently, it only creates another app folder with a date string containing a phpinfo.php file.)

Also. where can the Apache configuration be found?

**Comment by htuscher** [comment]
You can find the general documentation for the apache php images here: https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache.html

**Comment by htuscher** [comment]
Updated the mentioned things at https://github.com/webdevops/TYPO3-docker-boilerplate/commit/72c3d2ebc2c764d7e4c83f498585c328e8a76f38

**Comment by rowild** [comment]
@hhoechtl Thank you very much!
