### ISSUE TITLE
make create or make create-project?

### ISSUE THREAD

**Issue by inakiabt** [mblaschke/TYPO3-docker-boilerplate#66]
Based on the documentation ([PROJECT-EXISTING.md](https://github.com/mblaschke/TYPO3-docker-boilerplate/blob/develop/documentation%2FPROJECT-EXISTING.md), [PROJECT-NEOS.md](https://github.com/mblaschke/TYPO3-docker-boilerplate/blob/develop/documentation%2FPROJECT-NEOS.md), [PROJECT-SYMFONY.md](https://github.com/mblaschke/TYPO3-docker-boilerplate/blob/develop/documentation%2FPROJECT-SYMFONY.md), [PROJECT-TYPO3.md](https://github.com/mblaschke/TYPO3-docker-boilerplate/blob/develop/documentation%2FPROJECT-TYPO3.md)) the Makefile task should be `make create-project`, not `make create` (https://github.com/mblaschke/TYPO3-docker-boilerplate/blob/develop/Makefile#L9).

Or is the documentation wrong?

**Comment by mblaschke** [comment]
Should be `make create` but I'm unsure if i should keep this feature. Makefile doesn't support parameters for tasks and I've added this feature with a hack.

But you can deploy your web projects into `code/` directory. You don't have to use `make create`. Just `git clone`, `svn co` or `cp` your projects into `code/` :)

**Comment by mblaschke** [comment]
Next version of this docker boilerplate will focus on TYPO3.

For any other PHP project I've created a fork without the TYPO3 stuff:
https://github.com/mblaschke/php-docker-boilerplate

**Comment by htuscher** [comment]
Closed as it's no longer an issue
