### ISSUE TITLE
Improve Documentation: TYPO3 database settings

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#74]
Hallo,

I think a few words about the database settings in the install tool could be worthy. 

I finally found a working solution: `192.168.56.2:13306` 

I did `env | grep DOCK` plus `docker ps` to collect this information.

**Comment by mblaschke** [comment]
Currently they are available in https://github.com/webdevops/TYPO3-docker-boilerplate/blob/develop/documentation/DOCKER-INFO.md

Maybe not the best place, needs documentation refactoring

**Comment by elmar-hinz** [comment]
As a user I would need this information in the Chapter _Running TYPO3_. There is already an entry: _Webserver is available at Port 8000_

DRY: Put a link to the information. NEOS and other projects can then reuse it.
