### ISSUE TITLE
The startup breaks with: [8] System error: no such file or directory

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#75]
Strictly following the simple installation. After a successful build the initial startup of `main` fails. I tested this twice. The _TROUBLESHOUTING.md_ also doesn't help. The _main_ image is always failing after full rebuilds.

```
 xxx> git clone --recursive https://github.com/mblaschke/TYPO3-docker-boilerplate.git t3
 xxx> cd t3
 xxx> docker-compose up -d

 [ .... ]

Successfully built daa8e333716b
Creating t3_main_1...
Cannot start container e445cac1308aa5defd6971258c2890b0958d56a3e0ba9fe70cf8c3e39ca936fe:     [8] System error: no such file or directory
```

I run the docker server with https://github.com/webdevops/ with **Virtualbox** on this machine. 

```
 xxx> docker ps -a 

 CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                     NAMES

 e445cac1308a        t3_main             "/entrypoint.sh supe   12 minutes ago                                                    t3_main_1
 2e96f8dfedd2        t3_mysql            "/entrypoint.sh mysq   18 minutes ago      Up 18 minutes       0.0.0.0:13306->3306/tcp   t3_mysql_1
 035a0dcf84e2        t3_storage          "/entrypoint.sh noop   22 minutes ago      Up 22 minutes                                 t3_storage_1

 xxx> docker images
 REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
 t3_main                     latest              daa8e333716b        21 minutes ago      519.2 MB
 t3_mysql                    latest              300924ce0324        27 minutes ago      213.8 MB
 t3_storage                  latest              7239ae5a9051        31 minutes ago      188.4 MB
 webdevops/php-boilerplate   ubuntu-14.04        54c39e53b98e        3 hours ago         489.8 MB
ubuntu                      14.04               8251da35e7a7        2 days ago          188.4 MB
```

**Comment by mblaschke** [comment]
Have you moved the docker boilerplate directory?
Where is docker boilerplate stored? Inside VM or outside with NFS shares?

Have you tried to rebuild the whole docker boilerplate intance? (you will lose mysql and solr database):
`docker-compose stop`
`docker-compose rm --force`
`docker-compose build --no-cache`
`docker-compose up -d`

**Comment by elmar-hinz** [comment]
1.) My first guess is, to relate this issue to **Virtualbox**, as it is the rather unstable component.

2.) The TROUBLESHOUTING with uncached rebuild doesn't fix it.

3.) To my understanding https://github.com/webdevops/vagrant-development is mounting the docker directory onto the attached virtual drive: https://github.com/webdevops/vagrant-vm-disk.

However I want to test NFS mounting as an alternative to this virtual drive to be able to run the docker directory both with Parallels or Virtualbox interchangeably. So far there is nothing touched or moved.

**Comment by elmar-hinz** [comment]
```
# /etc/fstab of docker machine:

# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/vagrant--vg-root /               ext4    errors=remount-ro 0       1
UUID=7b30e244-7d1a-469e-ad01-1229aa4932a8 /boot           ext2    defaults        0       2
/dev/mapper/vagrant--vg-swap_1 none            swap    sw              0       0
/dev/sdb1 /mnt/data ext4 defaults 0 0
/mnt/data/docker /var/lib/docker/ none bind 0 0
/mnt/data/projects /home/vagrant/projects/ none bind 0 0
```

**Comment by mblaschke** [comment]
1.) VirtualBox is sometimes PITA because of unstable tcp connections. Parallels or VMware is faster and much more stable. If you're using MacOS you should use Parallels (vagrant plugin is free).

2.) I'm sorry but maybe it's just a VirtualBox issue :(

3.) Yes, it's a separate image because you can switch the filesystem (eg. to btrfs) for other features.

BTW: NFS issues should be visible in `dmesg`

**Comment by elmar-hinz** [comment]
Parallels requires a License on each of my machines and doesn't run on Linux at all. 

I still want to strive for a more general solution, a NFS mountable dockers directory on a USB stick that I can run on all physical Unix machines.

Hence, I am gonna try to find out the reason for this error myself. Will take some time.

**Comment by mblaschke** [comment]
USB can be unstable and also the mount points can be different for each box. I've not tested this so feel free to try it. 
Make sure that your USB connection is always stable or try to mount the USB stick inside the VM but I'm unsure if Vagrant can automatically connect the stick into VM.

For Linux VMware Workstation or KVM can be a good solution but i've not tested KVM.

IMHO:
yes it costs money but if you burn hours of working time VMware is not so expensive. I've already burned around 200-300 working hours because of VirtualBox bugs and my free time was not counted.

If you set a hourly rate of 10 Euro my lost time already costs 3000 Euro, if you use the full 80 Euro I've lost already 24.000 Euro in ~ 3 years.

VMware costs 300 Euro per seat? Not really expensive IMHO

The lost time of all other developers is not included and also not the frustrations because of bugs and low performance.

**Comment by mblaschke** [comment]
Oh.. but feel free to make your own experiences.
I'm much faster with Parallels and also I'm saving some hours of battery live if I'm working mobile :)

**Comment by elmar-hinz** [comment]
1.) Setting aside the costs data should never have proprietary bindings. So still striving for a general solution. Having that, nothing hinders me to fire up Parallels for reasons of costs.

2.) Stability: I used VirtualBox on USB Stick for years, without loss of data. In case there would be a backup. 

3.) Mounting: /Volums/XYZ/ is possible on OS X, BSD, Linux, any Unix.

4.)  Mount the USB stick inside the VM: Well, that I have to try.

**Comment by mblaschke** [comment]
1.) Put your stuff inside the VM and the issues are gone. We can't do anything about NFS/CIFS connection issues. :(
There are no proprietary bindings but only some stability issues with VirtualBox.

2.) Did you run Vagrant or just VMs from USB sticks?

3./4.) You can mount NFS/CIFS shares via Vagrant or just execute commands via SSH (like Ansible).
But i don't now if Vagrant is able to connect the USB stick into a VM automatically.

**Comment by elmar-hinz** [comment]
I tracked the issue down now. A missing mounted Volume inside the host vagrant-machine.

It was hard having only this error msg: `[8] System error: no such file or directory`

TYPO3-docker-boilerplate is sitting on `/Volumes/Work` which is symlinked from `/Users/ElmarHinz/Work`. 

The mount `/Volumes/Work` was not available inside _vagrant-development_. Hence, the following line inside \* docker-compose.yml\* was not resolvable.

```
  volumes:
    - ./:/docker/
```

The directory `./` could not be matched into _vagrant-development_, as the volume was not mounted.

**Comment by mblaschke** [comment]
Symlink.. oh :(
With the next Vagrant VM version (2.0) there will be an easy possibility to set shared folders but i think there is no solution to fix the symlink issue with NFS.
But it should be easier now to setup shared folders :)

see
https://github.com/webdevops/vagrant-development/blob/feature/refactor-vagrantfile/vm.yml#L77

All configuration options from `Vagrantfile` will be moved to `vm.yml` :)

**Comment by elmar-hinz** [comment]
I solved this with a line in the _Vagrantfile_.

```
 config.vm.synced_folder "/Volumes/Work/", "/Volumes/Work/", :nfs => { :mount_options => [ "dmode=775", "fmode=774" ] }
```

Resulting in this highjacked feature request: https://github.com/webdevops/vagrant-development/issues/62

This ticket can be closed. :)
