### ISSUE TITLE
Feedback: Mysql backup is working

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#88]
Just some positive feedback. I did the following test:
- Setup _TYPO3 version 7.x_ with _TYPO3-docker-boilerplate_.
- DB Backup with `make mysql-backup`. 
- Result: `backup/mysql.sql.bz2` was created.
- `docker ps -q | xargs docker rm -f` to remove the containers by brute force.
- `docker-compose up -d` for creating a fresh set of empty containers.
- `make mysql-restore` 
- Bingo. The page is up again.

I sent a Pull request to improve the mysql dump, with stored procedures, functions and comments.

**Comment by mblaschke** [comment]
Thanks for the feedback and I've merged the PR :)
