### ISSUE TITLE
docker-compose.yml.sample

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#93]
`docker-compose.yml` is part of the git repository. My private configuration always gets into the way, whenever I want to commit. 

Proposal:
- `move docker-compse.yml` to `docker-compose.yml.sample`
- `add docker-compse.yml` to `.gitignore`
- add a task `init` to the Makefile that creates `docker-compose.yml` if it doesn't exist.

**Comment by mblaschke** [comment]
This docker boilerplate should be a base for your own docker instance for each project and should stored inside your project's git.
That's why currently docker-compose.yml is inside the git repository.

**Comment by elmar-hinz** [comment]
I understand your approach. It's easy to deploy, but that has a price. It's more difficult to keep in sync with upstream.

The common pattern in software is, to separate program from configuration, so that updating becomes easy.

**Comment by chminngi** [comment]
Elmar I agree on that, I tried to externalize the own docker-compose.yml in another directory, ending up in having /docker/... misalignment in main container. I started two days ago to understand this project and would also like to have an own composer file outside.
I ended up temporarily with the following make target:

```
refresh:                                                                                                          
  rm -rf .git && git clone https://github.com/webdevops/TYPO3-docker-boilerplate.git tmp && mv tmp/.git . && rm - rf tmp && git reset --mixed                                                                                       

```

**Comment by mblaschke** [comment]
I will rename it to `docker-compose-local.yml` and `docker-compose-cloud.yml` (already included in `feature/cloud-support`.

You always can load custom named docker-compose.yml with: `docker-compose --file own-file.yml` :)

**Comment by mblaschke** [comment]
But is should still be a boilerplate - a template for your projects.. that's why i'm not sure about the renaming.. :/

**Comment by chminngi** [comment]
My question is: If I put an own docker-compose.yml in another directory and change the build pointers to ../<my-downloaded-TYPO3-boilerplate>/docker/main for example, everything is built well. But main is always shutting down, I guess because it does not find the physical directories. 

In other words I like to have an own directory beside the downloaded one and build relative, is it wise to adjust or make main and the other container relocatable, self-containing and at the end portable?

**Comment by mblaschke** [comment]
Make sure you've altered your `volume` paths inside `docker-compose.yml`.

Currently I'm refactoring (`feature/cloud-support) the php docker boilerplate (and also the TYPO3 docker boilerplate) to make them self-containing and portable but with another docker-compose file (docker-compose-cloud.yml).

Maybe it is a better solution to rename the `docker-compose.yml` from the boilerplate to `docker-compose-local.yml` so you can copy your favorite file to `docker-compose.yml`.
What do you think?

**Comment by chminngi** [comment]
temporarily yes, but If I need to customize other files I don't want to clutter the boilerplate directory, it's cleaner and easier to have own changes outside of it (*.yml, makefile, *.conf, ...)

**Comment by chminngi** [comment]
Markus at what time can we expect a refactored version?

**Comment by mblaschke** [comment]
Please give me some days and please remind me if this issue isn't resolved remind me if this issue isn't fixed this week :)

**Comment by mblaschke** [comment]
See branch `feature/cloud-support`

**Comment by elmar-hinz** [comment]
I often use **Symlinks** to draw configuration files from where I really keep the configuration. For private stuff this is my cloud drive, for public stuff it's my dotfile repository on github. I have not tried it here, yet.

**Comment by mblaschke** [comment]
There are now three example docker-compose.yml files, just symlink it to `docker-compose.yml` if you want to use the example.
